CREATE DATABASE FINANCIAL_DATA_ANALYSIS_1000ROWS;
USE FINANCIAL_DATA_ANALYSIS_1000ROWS;
DROP DATABASE FINANCIAL_DATA_ANALYSIS_1000ROWS;
DROP TABLE FINANCIAL_DATA_ANALYSIS_1000ROWS;

-- project title : Business Profitability Analysis using mysql 

SELECT * FROM FINANCIAL_DATA_ANALYSIS_1000ROWS;
-- 1️. TOTAL INCOME, EXPENSE, AND PROFIT
SELECT SUM(INCOME) AS TOTAL_INCOME,SUM(EXPENSE) AS TOTAL_EXPENSE,SUM(PROFIT) AS TOTAL_PROFIT FROM FINANCIAL_DATA_ANALYSIS_1000ROWS;

-- 2️. AVERAGE PROFIT BY DEPARTMENT
SELECT ROUND(AVG(PROFIT)) AS AVERAGE_PROFIT 
FROM FINANCIAL_DATA_ANALYSIS_1000ROWS 
GROUP BY DEPARTMENT 
ORDER BY AVERAGE_PROFIT;

-- 3.MONTHLY INCOME TREND
SELECT DATE_FORMAT(DATE, '%Y-%M') AS MONTH, ROUND(SUM(INCOME)) AS TOTAL_INCOME
FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
GROUP BY MONTH
ORDER BY MONTH;

-- 4️. MONTHLY PROFIT TREND
SELECT DATE_FORMAT(DATE,'%Y-%M')AS MONTH , ROUND(SUM(PROFIT)) AS TOTAL_PROFIT
FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
GROUP BY MONTH
ORDER BY MONTH;

-- 5.TOP 5 MOST PROFITABLE TRANSACTIONS
SELECT * FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
ORDER BY PROFIT DESC LIMIT 5;

-- 6️. DEPARTMENT-WISE TOTAL PROFIT
SELECT ROUND(SUM(PROFIT)) AS TOTAL_PROFIT FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
GROUP BY DEPARTMENT
ORDER BY TOTAL_PROFIT DESC;

-- 7.HIGH PROFIT MARGIN TRANSACTIONS (>50%)
SELECT * FROM FINANCIAL_DATA_ANALYSIS_1000ROWS 
WHERE PROFIT_MARGIN_PERCENTAGE > 50 
ORDER BY PROFIT_MARGIN_PERCENTAGE DESC;

-- 8️. AVERAGE EXPENSE PER MONTH
SELECT DATE_FORMAT(DATE, '%Y-%M') AS MONTH,ROUND(AVG(EXPENSE)) AS AVG_EXPENSE
FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
GROUP BY MONTH
ORDER BY MONTH;

-- 9️. PROFIT-EXPENSE RATIO BY DEPARTMENT
SELECT DEPARTMENT,
ROUND(SUM(PROFIT)/SUM(EXPENSE)) AS PROFIT_EXPENSE_RATIO
FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
GROUP BY DEPARTMENT
ORDER BY PROFIT_EXPENSE_RATIO DESC;

-- 10. Forecast Next Month Income (Simple Moving Average)
SELECT 
DATE_FORMAT(Date, '%Y-%m') AS Month,
round(AVG(Income) OVER (ORDER BY Date ROWS BETWEEN 29 PRECEDING AND CURRENT ROW)) AS Moving_Avg_Income
FROM FINANCIAL_DATA_ANALYSIS_1000ROWS
LIMIT 12;

/*
✅ These 10 queries cover:
Aggregate metrics
Department analysis
Monthly trends
Top transactions
Profitability insights
*/